"""Typed schemas for company-strategy crisis simulation."""

from datetime import datetime
from typing import Literal

from pydantic import AliasChoices, BaseModel, Field, model_validator


class CrisisReport(BaseModel):
    """Structured business disruption output."""

    disruption_event: Literal[
        "supply_chain_disruption",
        "sudden_demand_drop",
        "competitor_launching_cheaper_product",
        "economic_recession",
        "manufacturing_cost_spike",
    ]
    supply_chain_disruption: float = Field(..., ge=0.0, le=1.0)
    demand_drop_intensity: float = Field(..., ge=0.0, le=1.0)
    competitor_price_pressure: float = Field(..., ge=0.0, le=1.0)
    recession_pressure: float = Field(..., ge=0.0, le=1.0)
    manufacturing_cost_spike: float = Field(..., ge=0.0, le=1.0)
    severity_index: float = Field(..., ge=0.0, le=1.0)


class CEOProfile(BaseModel):
    """Archetype trait profile."""

    name: str
    risk_tolerance: float = Field(..., ge=0.0, le=1.0)
    innovation_bias: float = Field(..., ge=0.0, le=1.0)
    liquidity_priority: float = Field(..., ge=0.0, le=1.0)
    cost_sensitivity: float = Field(..., ge=0.0, le=1.0)
    long_term_focus: float = Field(..., ge=0.0, le=1.0)


class CompanyState(BaseModel):
    """Company environment variables replacing trading inputs."""

    product_demand: float = Field(..., ge=0.0, le=1.0)
    production_cost: float = Field(..., ge=0.0, le=1.0)
    supply_chain_risk: float = Field(..., ge=0.0, le=1.0)
    competitor_pressure: float = Field(..., ge=0.0, le=1.0)
    marketing_effectiveness: float = Field(..., ge=0.0, le=1.0)
    customer_sentiment: float = Field(..., ge=0.0, le=1.0)
    cash_reserves: float = Field(..., ge=0.0, le=1.0)

    @model_validator(mode="before")
    @classmethod
    def _coerce_legacy_financial_state(cls, data):
        """Backwards-compatible mapper from legacy financial payload shape."""

        if not isinstance(data, dict):
            return data

        required = {
            "product_demand",
            "production_cost",
            "supply_chain_risk",
            "competitor_pressure",
            "marketing_effectiveness",
            "customer_sentiment",
            "cash_reserves",
        }
        if required.issubset(data.keys()):
            return data

        if {"revenue", "cash", "burn_rate", "liquidity_months"}.issubset(data.keys()):
            revenue = float(data.get("revenue", 1.0))
            burn_rate = float(data.get("burn_rate", 0.0))
            cash = float(data.get("cash", 0.0))
            liquidity_months = float(data.get("liquidity_months", 0.0))

            return {
                "product_demand": max(0.0, min(1.0, revenue / 20_000_000)),
                "production_cost": max(0.0, min(1.0, burn_rate / max(revenue, 1.0) * 2.5)),
                "supply_chain_risk": max(0.0, min(1.0, 1.0 - min(liquidity_months / 24.0, 1.0))),
                "competitor_pressure": 0.45,
                "marketing_effectiveness": 0.55,
                "customer_sentiment": 0.58,
                "cash_reserves": max(0.0, min(1.0, cash / 12_000_000)),
            }
        return data


class CompanyQuarterMetrics(BaseModel):
    """Business outcomes for one quarter."""

    revenue: float = Field(..., ge=0.0)
    profit_margin: float = Field(..., ge=0.0, le=1.0)
    market_share: float = Field(..., ge=0.0, le=1.0)
    customer_growth: float = Field(..., ge=-1.0, le=1.0)
    brand_strength: float = Field(..., ge=0.0, le=1.0)
    company_cash_balance: float = Field(..., ge=0.0)


class Explainability(BaseModel):
    """Structured explainability vectors for auditability."""

    dominant_factors: list[str]
    severity_context: float = Field(..., ge=0.0, le=1.0)


class MarketSentimentSignal(BaseModel):
    """Signal generated by market intelligence advisory agent."""

    sentiment_score: float = Field(..., ge=-1.0, le=1.0)
    momentum_signal: float = Field(..., ge=0.0, le=1.0)
    volatility_pressure: float = Field(..., ge=0.0, le=1.0)
    adjustment: float = Field(..., ge=-1.0, le=1.0)


class OperationsSignal(BaseModel):
    """Signal generated by innovation/operations advisory agent."""

    efficiency_score: float = Field(..., ge=0.0, le=1.0)
    opex_pressure: float = Field(..., ge=0.0, le=1.0)
    execution_risk: float = Field(..., ge=0.0, le=1.0)
    adjustment: float = Field(..., ge=-1.0, le=1.0)


class TreasurySignal(BaseModel):
    """Signal generated by finance/treasury advisory agent."""

    liquidity_health: float = Field(..., ge=0.0, le=1.0)
    runway_pressure: float = Field(..., ge=0.0, le=1.0)
    refinancing_risk: float = Field(..., ge=0.0, le=1.0)
    adjustment: float = Field(..., ge=-1.0, le=1.0)


class SupportAgentSignals(BaseModel):
    """Combined outputs from specialized support agents."""

    market_sentiment: MarketSentimentSignal
    operations: OperationsSignal
    treasury: TreasurySignal
    aggregate_adjustment: float = Field(..., ge=-1.0, le=1.0)
    dominant_driver: str


class CEODecision(BaseModel):
    """Structured CEO strategic action output."""

    strategy: Literal[
        "increase_marketing",
        "cut_production",
        "invest_in_r_and_d",
        "adjust_price",
        "hire_or_layoff_staff",
        "enter_new_market",
    ]
    risk_level: float = Field(..., ge=0.0, le=1.0)
    growth_score: float
    stability_score: float
    strategy_index: float
    quarter_metrics: CompanyQuarterMetrics
    updated_traits: CEOProfile
    explainability: Explainability
    support_signals: SupportAgentSignals | None = None


class MemoryRecord(BaseModel):
    """Memory unit storing decision and outcome signals."""

    timestamp: datetime
    profile_name: str
    strategy: str
    pre_traits: CEOProfile
    post_traits: CEOProfile
    strategy_index: float
    outcome_success: bool
    liquidity_delta: float


class SimulationRequest(BaseModel):
    """API request for a full multi-agent company cycle."""

    archetype: Literal["VisionaryInnovator", "ConservativeStabilizer"]
    company_state: CompanyState = Field(
        validation_alias=AliasChoices("company_state", "financial_state"),
        serialization_alias="company_state",
    )
    seed: int | None = None
    outcome_success: bool | None = None
    liquidity_delta: float | None = None


class SimulationResponse(BaseModel):
    """API response with crisis report + CEO decision."""

    crisis_report: CrisisReport
    ceo_decision: CEODecision


class TimelineSimulationRequest(BaseModel):
    """API request for multi-quarter timeline simulation."""

    archetype: Literal["VisionaryInnovator", "ConservativeStabilizer"]
    company_state: CompanyState = Field(
        validation_alias=AliasChoices("company_state", "financial_state"),
        serialization_alias="company_state",
    )
    quarters: int = Field(default=8, ge=1, le=40)
    seed: int | None = None


class QuarterTimelinePoint(BaseModel):
    """Quarter-by-quarter simulation output point."""

    quarter: int = Field(..., ge=1)
    crisis: CrisisReport
    decision: CEODecision
    company_state: CompanyState


class TimelineSimulationResponse(BaseModel):
    """Timeline simulation response payload."""

    quarters: list[QuarterTimelinePoint]
    market_share_evolution: list[float]
    final_resilience_score: float = Field(..., ge=0.0, le=1.0)


class LiveSimulationStartRequest(BaseModel):
    """Request payload to start a continuous company simulation session."""

    archetype: Literal["VisionaryInnovator", "ConservativeStabilizer"]
    company_state: CompanyState = Field(
        validation_alias=AliasChoices("company_state", "financial_state"),
        serialization_alias="company_state",
    )
    tick_seconds: float = Field(default=1.5, ge=0.4, le=10.0)
    max_quarters: int = Field(default=24, ge=1, le=120)
    seed: int | None = None


class LiveSimulationStartResponse(BaseModel):
    """Response payload for started live simulation session."""

    session_id: str
    archetype: str
    tick_seconds: float
    max_quarters: int
